## **Задание на повторение материала
<h4> 1. Создать одномерный массив Numpy под названием a из 12 последовательных целых чисел чисел от 12 до 24 невключительно


In [1]:
import numpy as np

In [2]:
a = np.linspace(12, 23, 12)
a

array([12., 13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23.])

<h4> 2. Создать 5 двумерных массивов разной формы из массива a. Не использовать в аргументах метода reshape число -1.


In [3]:
a.resize(3, 4)
print(a)

[[12. 13. 14. 15.]
 [16. 17. 18. 19.]
 [20. 21. 22. 23.]]


In [4]:
a2 = a.T
a2

array([[12., 16., 20.],
       [13., 17., 21.],
       [14., 18., 22.],
       [15., 19., 23.]])

In [5]:
a3 = np.random.choice(a.flatten(), (2, 6))
a3


array([[16., 15., 22., 21., 17., 16.],
       [15., 12., 19., 15., 14., 14.]])

In [6]:
a4=a.reshape(6, 2)
print(a4)

[[12. 13.]
 [14. 15.]
 [16. 17.]
 [18. 19.]
 [20. 21.]
 [22. 23.]]


In [7]:
a5=a.reshape(6, 2).T
print(a5)

[[12. 14. 16. 18. 20. 22.]
 [13. 15. 17. 19. 21. 23.]]


In [8]:
a6=a.reshape(4, 3)
print(a6)

[[12. 13. 14.]
 [15. 16. 17.]
 [18. 19. 20.]
 [21. 22. 23.]]


In [9]:
a7=a.reshape(4, 3).T
print(a7)

[[12. 15. 18. 21.]
 [13. 16. 19. 22.]
 [14. 17. 20. 23.]]


In [10]:
a8=a.reshape(12, 1)
print(a8)

[[12.]
 [13.]
 [14.]
 [15.]
 [16.]
 [17.]
 [18.]
 [19.]
 [20.]
 [21.]
 [22.]
 [23.]]


In [11]:
a9=a.reshape(1, 12)
print(a9)

[[12. 13. 14. 15. 16. 17. 18. 19. 20. 21. 22. 23.]]


<h4> 3. Создать 5 двумерных массивов разной формы из массива a. Использовать в аргументах метода reshape число -1 (в трех примерах - для обозначения числа столбцов, в двух - для строк).

In [12]:
a.reshape(2, -1)

array([[12., 13., 14., 15., 16., 17.],
       [18., 19., 20., 21., 22., 23.]])

In [13]:
a.reshape(3, -1)

array([[12., 13., 14., 15.],
       [16., 17., 18., 19.],
       [20., 21., 22., 23.]])

In [14]:
a.reshape(4, -1)

array([[12., 13., 14.],
       [15., 16., 17.],
       [18., 19., 20.],
       [21., 22., 23.]])

In [15]:
a.reshape(-1, 2)

array([[12., 13.],
       [14., 15.],
       [16., 17.],
       [18., 19.],
       [20., 21.],
       [22., 23.]])

In [16]:
a.reshape(-1, 4)

array([[12., 13., 14., 15.],
       [16., 17., 18., 19.],
       [20., 21., 22., 23.]])

<h4>4. Можно ли массив Numpy, состоящий из одного столбца и 12 строк, назвать одномерным?  -  <i> Нет </i>


In [17]:
type(a.reshape(12, 1))

numpy.ndarray

In [18]:
print("Размерность a: {}".format((a.reshape(12, 1)).ndim))


Размерность a: 2


<b><i>Ответ: Нет, массив Numpy, состоящий из одного столбца и 12 строк, назвать одномерным нельзя. Размерность a: 2</i></b>

<h4> 5. Создать массив из 3 строк и 4 столбцов, состоящий из случайных чисел с плавающей запятой из нормального распределения со средним, равным 0 и среднеквадратичным отклонением, равным 1.0. Получить из этого массива одномерный массив с таким же атрибутом size, как и исходный массив.

In [19]:
b = np.random.randn(3, 4)
print(b)
print(b.size)

[[-0.5224305  -0.19977318 -0.99294819  0.32887067]
 [-1.56517247  3.02686529  0.03673043 -0.62297161]
 [ 0.54562969 -1.12522042  1.0579623  -0.68869743]]
12


In [20]:
c = b.flatten()
print(c)
print(c.size)

[-0.5224305  -0.19977318 -0.99294819  0.32887067 -1.56517247  3.02686529
  0.03673043 -0.62297161  0.54562969 -1.12522042  1.0579623  -0.68869743]
12


<h4> 6. Создать массив a, состоящий из целых чисел, убывающих от 20 до 0 невключительно с интервалом 2.

In [21]:
a = np.arange(20, 0, -2)
print(a)

[20 18 16 14 12 10  8  6  4  2]


<h4> 7. Создать массив b, состоящий из 1 строки и 10 столбцов: целых чисел, убывающих от 20 до 1 невключительно с интервалом 2. В чем разница между массивами a и b?

In [22]:
b = (np.arange(20, 1, -2)).reshape(1, -1)
print(b)

[[20 18 16 14 12 10  8  6  4  2]]


In [23]:
print(type(a))
print("Размерность a: {}".format(a.ndim))

<class 'numpy.ndarray'>
Размерность a: 1


In [24]:
print(type(b))
print("Размерность b: {}".format(b.ndim))

<class 'numpy.ndarray'>
Размерность b: 2


<b><i> Ответ: Массив а - одномерный, массив b - двумерный.</i></b>

<h4> 8. Вертикально соединить массивы a и b. a - двумерный массив из нулей, число строк которого больше 1 и на 1 меньше, чем число строк двумерного массива b, состоящего из единиц. Итоговый массив v должен иметь атрибут size, равный 10.

In [25]:
a = np.zeros((2, 2))
print(a)

[[0. 0.]
 [0. 0.]]


In [26]:
b = np.ones((3, 2))
print(b)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [27]:
v = np.concatenate((a, b), axis=0)
print(v)

[[0. 0.]
 [0. 0.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [28]:
print(v.size)

10


<h4> 9. Создать одномерный массив а, состоящий из последовательности целых чисел от 0 до 12. Поменять форму этого массива, чтобы получилась матрица A (двумерный массив Numpy), состоящая из 4 строк и 3 столбцов. Получить матрицу At путем транспонирования матрицы A. Получить матрицу B, умножив матрицу A на матрицу At с помощью матричного умножения. Какой размер имеет матрица B? Получится ли вычислить обратную матрицу для матрицы B и почему?

In [29]:
a = np.arange(0, 12)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [30]:
A = a.reshape(4, 3)
print(A)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [31]:
At = A.T
print(At)

[[ 0  3  6  9]
 [ 1  4  7 10]
 [ 2  5  8 11]]


In [32]:
B = A.dot(At)
print(B)
print(B.size)

[[  5  14  23  32]
 [ 14  50  86 122]
 [ 23  86 149 212]
 [ 32 122 212 302]]
16


In [33]:
np.linalg.det(B)

0.0

In [34]:
np.linalg.inv(B)

LinAlgError: Singular matrix

<b><i>Ответ: определитель квадратной матрицы B равен 0, это значит, что мы не можем посчитать для неё обратную матрицу. np.linalg.inv(B) - выдает ошибку. </i></b>

 <h4>10. Инициализируйте генератор случайных числе с помощью объекта seed, равного 42.

In [38]:
import random
random.seed(42)

<h4> 11. Создайте одномерный массив c, составленный из последовательности 16-ти случайных равномерно распределенных целых чисел от 0 до 16 невключительно. 


In [42]:
c = np.arange(0, 16)
print(c)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


<h4> 12. Поменяйте его форму так, чтобы получилась квадратная матрица C. Получите матрицу D, поэлементно прибавив матрицу B из предыдущего вопроса к матрице C, умноженной на 10. Вычислите определитель, ранг и обратную матрицу D_inv для D.

In [60]:
C = c.reshape(4, 4)
print(C)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [65]:
D = B + C*10
print(D)

[[  5  24  43  62]
 [ 54 100 146 192]
 [103 176 249 322]
 [152 252 352 452]]


In [69]:
d = np.linalg.det(D)
print('Определитель равен: ', d)

Определитель равен:  -7.685903354004529e-25


In [70]:
r = np.linalg.matrix_rank(D)
print('ранг равен: ', r)

ранг равен:  2


In [94]:
D_inv = np.linalg.inv(D)
print(D_inv)

[[ 1.10382344e+13  5.26315789e-02 -3.31147031e+13  2.20764688e+13]
 [-8.46264636e+13  9.38249922e+13  6.62294063e+13 -7.54279349e+13]
 [ 1.36138224e+14 -1.87649984e+14 -3.31147031e+13  8.46264636e+13]
 [-6.25499948e+13  9.38249922e+13  0.00000000e+00 -3.12749974e+13]]


In [95]:
print(D.dot(D_inv))

[[ 1.5  -1.    0.    0.75]
 [ 2.    0.    0.    2.  ]
 [ 4.   -4.    1.    2.  ]
 [ 0.    0.    0.    2.  ]]


<h4> 13. Приравняйте к нулю отрицательные числа в матрице D_inv, а положительные - к единице. Убедитесь, что в матрице D_inv остались только нули и единицы. С помощью функции numpy.where, используя матрицу D_inv в качестве маски, а матрицы B и C - в качестве источников данных, получите матрицу E размером 4x4.  Элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 1, должны быть равны соответствующему элементу матрицы B, а элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 0, должны быть равны соответствующему элементу матрицы C.


In [107]:
print(D_inv)

[[ 1.10382344e+13  5.26315789e-02 -3.31147031e+13  2.20764688e+13]
 [-8.46264636e+13  9.38249922e+13  6.62294063e+13 -7.54279349e+13]
 [ 1.36138224e+14 -1.87649984e+14 -3.31147031e+13  8.46264636e+13]
 [-6.25499948e+13  9.38249922e+13  0.00000000e+00 -3.12749974e+13]]


In [114]:
for i in D_inv: print(i[i > 0])

[1.10382344e+13 5.26315789e-02 2.20764688e+13]
[9.38249922e+13 6.62294063e+13]
[1.36138224e+14 8.46264636e+13]
[9.38249922e+13]


In [167]:
for i in D_inv:
    print((i[i > 0]).append(1));
#print(D_inv)

AttributeError: 'numpy.ndarray' object has no attribute 'append'

In [ ]:
def D_new (X):
    X = i in X

    X.loc[X[i] > 0] = 1  
    X.loc[X[i] < 0] = 0

    return X

In [ ]:
df = D_new(D_inv)
df